var searchData=
[
  ['utils_20for_20debug_20device_20code_329',['utils for debug device code',['../group__Debug.html',1,'']]],
  ['uniform_5fselector_5ft_330',['uniform_selector_t',['../structcugraph_1_1detail_1_1uniform__selector__t.html',1,'cugraph::detail']]],
  ['unrenumber_5fint_5fvertices_331',['unrenumber_int_vertices',['../namespacecugraph.html#aa7b7a7d3c7feeb4c367ad02b80d6df05',1,'cugraph']]],
  ['unrenumber_5flocal_5fint_5fedges_332',['unrenumber_local_int_edges',['../namespacecugraph.html#a14d7f0ff2d4c0d3d657c33c4577d6ef3',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_rows, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_cols, std::vector&lt; size_t &gt; const  &amp;edgelist_edge_counts, vertex_t const  *renumber_map_labels, std::vector&lt; vertex_t &gt; const  &amp;vertex_partition_lasts, std::optional&lt; std::vector&lt; std::vector&lt; size_t &gt;&gt;&gt; const  &amp;edgelist_intra_partition_segment_offsets, bool do_expensive_check=false)'],['../namespacecugraph.html#ac3613b6995638d34ff5d7a8be5e355e8',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, vertex_t *edgelist_rows, vertex_t *edgelist_cols, size_t num_edgelist_edges, vertex_t const  *renumber_map_labels, vertex_t num_vertices, bool do_expensive_check=false)']]],
  ['unrenumber_5flocal_5fint_5fvertices_333',['unrenumber_local_int_vertices',['../namespacecugraph.html#ab2d2829de3b33d7f394c8a1ff5169ca5',1,'cugraph']]],
  ['update_5ffrontier_5fv_5fpush_5fif_5fout_5fnbr_334',['update_frontier_v_push_if_out_nbr',['../namespacecugraph.html#ad18b474e61601d1b82dad8dd10d7f505',1,'cugraph']]],
  ['update_5fpaths_335',['update_paths',['../structcugraph_1_1detail_1_1update__paths.html',1,'cugraph::detail']]],
  ['update_5ftuple_5ffrom_5fvector_5fof_5ftuple_5fscalar_5felements_5fimpl_336',['update_tuple_from_vector_of_tuple_scalar_elements_impl',['../structcugraph_1_1detail_1_1update__tuple__from__vector__of__tuple__scalar__elements__impl.html',1,'cugraph::detail']]],
  ['update_5ftuple_5ffrom_5fvector_5fof_5ftuple_5fscalar_5felements_5fimpl_3c_20tupletype_2c_20i_2c_20i_20_3e_337',['update_tuple_from_vector_of_tuple_scalar_elements_impl&lt; TupleType, I, I &gt;',['../structcugraph_1_1detail_1_1update__tuple__from__vector__of__tuple__scalar__elements__impl_3_01TupleType_00_01I_00_01I_01_4.html',1,'cugraph::detail']]],
  ['update_5fvector_5fof_5ftuple_5fscalar_5felements_5ffrom_5ftuple_5fimpl_338',['update_vector_of_tuple_scalar_elements_from_tuple_impl',['../structcugraph_1_1detail_1_1update__vector__of__tuple__scalar__elements__from__tuple__impl.html',1,'cugraph::detail']]],
  ['update_5fvector_5fof_5ftuple_5fscalar_5felements_5ffrom_5ftuple_5fimpl_3c_20tupletype_2c_20i_2c_20i_20_3e_339',['update_vector_of_tuple_scalar_elements_from_tuple_impl&lt; TupleType, I, I &gt;',['../structcugraph_1_1detail_1_1update__vector__of__tuple__scalar__elements__from__tuple__impl_3_01TupleType_00_01I_00_01I_01_4.html',1,'cugraph::detail']]],
  ['updatedevice_340',['updateDevice',['../group__Copy.html#ga18a265a5eb16da13a51f486fe5e3acb7',1,'MLCommon']]],
  ['updatehost_341',['updateHost',['../group__Copy.html#ga9c1498ebc5825f9e63a9de94ced042d5',1,'MLCommon']]]
];
