rules:
  unpinned-uses:
    config:
      policies:
        # Require SHA-pinning except for RAPIDS-managed reusable actions and workflows.
        "rapidsai/shared-workflows/*": any
        "rapidsai/shared-actions/*": any
        "*": hash-pin
