# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

[build]
command = "python -m pip install uv && uv sync --locked && make html"
publish = "_site"

[build.environment]
PYTHON_VERSION = "3.14"
