var searchData=
[
  ['data_5fsink_1665',['data_sink',['../classcudf_1_1io_1_1data__sink.html',1,'cudf::io']]],
  ['data_5ftype_1666',['data_type',['../classcudf_1_1data__type.html',1,'cudf']]],
  ['datasource_1667',['datasource',['../classcudf_1_1io_1_1datasource.html',1,'cudf::io']]],
  ['decimal_5fstatistics_1668',['decimal_statistics',['../structcudf_1_1io_1_1decimal__statistics.html',1,'cudf::io']]],
  ['device_5fbuffer_1669',['device_buffer',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1device__buffer.html',1,'rmm']]],
  ['device_5fmemory_5fresource_1670',['device_memory_resource',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1mr_1_1device__memory__resource.html',1,'rmm::mr']]],
  ['device_5fscalar_1671',['device_scalar',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20bool_20_3e_1672',['device_scalar&lt; bool &gt;',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20rep_5ftype_20_3e_1673',['device_scalar&lt; rep_type &gt;',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20t_20_3e_1674',['device_scalar&lt; T &gt;',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fspan_1675',['device_span',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fuvector_1676',['device_uvector',['https://docs.rapids.ai/api/librmm/21.08/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['dictionary_5fcolumn_5fview_1677',['dictionary_column_view',['../classcudf_1_1dictionary__column__view.html',1,'cudf']]],
  ['dictionary_5fcolumn_5fwrapper_1678',['dictionary_column_wrapper',['../classcudf_1_1test_1_1dictionary__column__wrapper.html',1,'cudf::test']]],
  ['dictionary_5fcolumn_5fwrapper_3c_20std_3a_3astring_20_3e_1679',['dictionary_column_wrapper&lt; std::string &gt;',['../classcudf_1_1test_1_1dictionary__column__wrapper_3_01std_1_1string_01_4.html',1,'cudf::test']]],
  ['dictionary_5fwrapper_1680',['dictionary_wrapper',['../structcudf_1_1dictionary__wrapper.html',1,'cudf']]],
  ['dispatch_5fstorage_5ftype_1681',['dispatch_storage_type',['../structcudf_1_1dispatch__storage__type.html',1,'cudf']]],
  ['double_5fstatistics_1682',['double_statistics',['../structcudf_1_1io_1_1double__statistics.html',1,'cudf::io']]],
  ['double_5ftype_5fdispatcher_5ffirst_5ftype_1683',['double_type_dispatcher_first_type',['../structcudf_1_1detail_1_1double__type__dispatcher__first__type.html',1,'cudf::detail']]],
  ['double_5ftype_5fdispatcher_5fsecond_5ftype_1684',['double_type_dispatcher_second_type',['../structcudf_1_1detail_1_1double__type__dispatcher__second__type.html',1,'cudf::detail']]],
  ['duration_5fscalar_1685',['duration_scalar',['../classcudf_1_1duration__scalar.html',1,'cudf']]],
  ['duration_5fscalar_5fdevice_5fview_1686',['duration_scalar_device_view',['../classcudf_1_1duration__scalar__device__view.html',1,'cudf']]],
  ['dynamic_1687',['DYNAMIC',['../structcudf_1_1contains__nulls_1_1DYNAMIC.html',1,'cudf::contains_nulls']]]
];
