var searchData=
[
  ['scalar_1953',['scalar',['../classcudf_1_1scalar.html',1,'cudf::scalar'],['../structcudf_1_1detail_1_1scalar__factory_1_1scalar.html',1,'cudf::detail::scalar_factory::scalar&lt; T &gt;']]],
  ['scalar_5fdevice_5fview_5fbase_1954',['scalar_device_view_base',['../classcudf_1_1detail_1_1scalar__device__view__base.html',1,'cudf::detail']]],
  ['scalar_5ffactory_1955',['scalar_factory',['../structcudf_1_1detail_1_1scalar__factory.html',1,'cudf::detail']]],
  ['scalar_5fpair_5faccessor_1956',['scalar_pair_accessor',['../structcudf_1_1experimental_1_1detail_1_1scalar__pair__accessor.html',1,'cudf::experimental::detail']]],
  ['scalar_5fscatterer_1957',['scalar_scatterer',['../structcudf_1_1detail_1_1scalar__scatterer.html',1,'cudf::detail']]],
  ['scalar_5fvalue_5faccessor_1958',['scalar_value_accessor',['../structcudf_1_1experimental_1_1detail_1_1scalar__value__accessor.html',1,'cudf::experimental::detail']]],
  ['scaled_5finteger_1959',['scaled_integer',['../structnumeric_1_1scaled__integer.html',1,'numeric']]],
  ['scandispatcher_1960',['ScanDispatcher',['../structcudf_1_1experimental_1_1detail_1_1ScanDispatcher.html',1,'cudf::experimental::detail']]],
  ['schema_5fentry_1961',['schema_entry',['../structcudf_1_1io_1_1avro_1_1schema__entry.html',1,'cudf::io::avro']]],
  ['schema_5fparser_1962',['schema_parser',['../classcudf_1_1io_1_1avro_1_1schema__parser.html',1,'cudf::io::avro']]],
  ['schemadesc_5fs_1963',['schemadesc_s',['../structcudf_1_1io_1_1avro_1_1gpu_1_1schemadesc__s.html',1,'cudf::io::avro::gpu']]],
  ['schemaelement_1964',['SchemaElement',['../structcudf_1_1io_1_1parquet_1_1SchemaElement.html',1,'cudf::io::parquet']]],
  ['schematype_1965',['SchemaType',['../structcudf_1_1io_1_1orc_1_1SchemaType.html',1,'cudf::io::orc']]],
  ['scoped_5fstream_1966',['scoped_stream',['../structcudf_1_1util_1_1cuda_1_1scoped__stream.html',1,'cudf::util::cuda']]],
  ['scratch_5farr_1967',['scratch_arr',['../structcudf_1_1io_1_1scratch__arr.html',1,'cudf::io']]],
  ['serialtrienode_1968',['SerialTrieNode',['../structSerialTrieNode.html',1,'']]],
  ['simple_5fop_1969',['simple_op',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20max_20_3e_1970',['simple_op&lt; max &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20mean_20_3e_1971',['simple_op&lt; mean &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20min_20_3e_1972',['simple_op&lt; min &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20product_20_3e_1973',['simple_op&lt; product &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20standard_5fdeviation_20_3e_1974',['simple_op&lt; standard_deviation &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20sum_20_3e_1975',['simple_op&lt; sum &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20sum_5fof_5fsquares_20_3e_1976',['simple_op&lt; sum_of_squares &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20variance_20_3e_1977',['simple_op&lt; variance &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['sink_5finfo_1978',['sink_info',['../structcudf_1_1experimental_1_1io_1_1sink__info.html',1,'cudf::experimental::io::sink_info'],['../structcudf_1_1sink__info.html',1,'cudf::sink_info']]],
  ['size_5fof_5fhelper_1979',['size_of_helper',['../structcudf_1_1detail_1_1size__of__helper.html',1,'cudf::detail']]],
  ['snap_5fstate_5fs_1980',['snap_state_s',['../structcudf_1_1io_1_1snap__state__s.html',1,'cudf::io']]],
  ['sort_5fgroupby_5fhelper_1981',['sort_groupby_helper',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1sort_1_1sort__groupby__helper.html',1,'cudf::experimental::groupby::detail::sort']]],
  ['source_5finfo_1982',['source_info',['../structcudf_1_1experimental_1_1io_1_1source__info.html',1,'cudf::experimental::io::source_info'],['../structcudf_1_1source__info.html',1,'cudf::source_info']]],
  ['special_5fcase_5fmapping_1983',['special_case_mapping',['../structcudf_1_1strings_1_1detail_1_1special__case__mapping.html',1,'cudf::strings::detail']]],
  ['standard_5fdeviation_1984',['standard_deviation',['../structcudf_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::reduction::op::standard_deviation'],['../structcudf_1_1experimental_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::experimental::reduction::op::standard_deviation']]],
  ['statistics_5fchunk_1985',['statistics_chunk',['../structcudf_1_1io_1_1statistics__chunk.html',1,'cudf::io']]],
  ['statistics_5fgroup_1986',['statistics_group',['../structcudf_1_1io_1_1statistics__group.html',1,'cudf::io']]],
  ['statistics_5fmerge_5fgroup_1987',['statistics_merge_group',['../structcudf_1_1io_1_1statistics__merge__group.html',1,'cudf::io']]],
  ['statistics_5fval_1988',['statistics_val',['../unioncudf_1_1io_1_1statistics__val.html',1,'cudf::io']]],
  ['stats_1989',['stats',['../structcudf_1_1io_1_1csv_1_1column__parse_1_1stats.html',1,'cudf::io::csv::column_parse']]],
  ['stats_5fcolumn_5fdesc_1990',['stats_column_desc',['../structcudf_1_1io_1_1stats__column__desc.html',1,'cudf::io']]],
  ['stats_5fstate_5fs_1991',['stats_state_s',['../structcudf_1_1io_1_1stats__state__s.html',1,'cudf::io::stats_state_s'],['../structcudf_1_1io_1_1orc_1_1gpu_1_1stats__state__s.html',1,'cudf::io::orc::gpu::stats_state_s']]],
  ['std_5fargs_1992',['std_args',['../structcudf_1_1groupby_1_1sort_1_1std__args.html',1,'cudf::groupby::sort']]],
  ['std_5fvar_5faggregation_1993',['std_var_aggregation',['../structcudf_1_1experimental_1_1detail_1_1std__var__aggregation.html',1,'cudf::experimental::detail']]],
  ['store_5foutput_5ffunctor_1994',['store_output_functor',['../structcudf_1_1detail_1_1store__output__functor.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20_5ft_2c_20true_20_3e_1995',['store_output_functor&lt; _T, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01__T_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20columntype_2c_20true_20_3e_1996',['store_output_functor&lt; ColumnType, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01ColumnType_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5fresult_5ffunctor_1997',['store_result_functor',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1store__result__functor.html',1,'cudf::experimental::groupby::detail']]],
  ['strdata_5fenc_5fstate_5fs_1998',['strdata_enc_state_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1strdata__enc__state__s.html',1,'cudf::io::orc::gpu']]],
  ['stream_1999',['Stream',['../structcudf_1_1io_1_1orc_1_1Stream.html',1,'cudf::io::orc']]],
  ['string_5fscalar_2000',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fscalar_5fdevice_5fview_2001',['string_scalar_device_view',['../classcudf_1_1string__scalar__device__view.html',1,'cudf']]],
  ['string_5fstats_2002',['string_stats',['../structcudf_1_1io_1_1string__stats.html',1,'cudf::io']]],
  ['string_5fview_2003',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['string_5fview_5fto_5fpair_2004',['string_view_to_pair',['../structcudf_1_1string__view__to__pair.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_2005',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['strings_5ftokenizer_2006',['strings_tokenizer',['../structnvtext_1_1detail_1_1strings__tokenizer.html',1,'nvtext::detail']]],
  ['stripedictionary_2007',['StripeDictionary',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeDictionary.html',1,'cudf::io::orc::gpu']]],
  ['stripefooter_2008',['StripeFooter',['../structcudf_1_1io_1_1orc_1_1StripeFooter.html',1,'cudf::io::orc']]],
  ['stripeinformation_2009',['StripeInformation',['../structcudf_1_1io_1_1orc_1_1StripeInformation.html',1,'cudf::io::orc']]],
  ['stripestatistics_2010',['StripeStatistics',['../structcudf_1_1io_1_1orc_1_1StripeStatistics.html',1,'cudf::io::orc']]],
  ['stripestream_2011',['StripeStream',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeStream.html',1,'cudf::io::orc::gpu']]],
  ['sum_2012',['sum',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1sum.html',1,'cudf::experimental::reduction::op::sum'],['../structcudf_1_1reduction_1_1op_1_1sum.html',1,'cudf::reduction::op::sum']]],
  ['sum_5fof_5fsquares_2013',['sum_of_squares',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::experimental::reduction::op::sum_of_squares'],['../structcudf_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::reduction::op::sum_of_squares']]]
];
