var searchData=
[
  ['utils_20for_20debug_20device_20code_384',['utils for debug device code',['../group__Debug.html',1,'']]],
  ['uniform_5fnbr_5fsample_385',['uniform_nbr_sample',['../namespacecugraph.html#a8ff43a61abf7eb1ae79d364b2d7cebb1',1,'cugraph::uniform_nbr_sample(raft::handle_t const  &amp;handle, graph_view_t const  &amp;graph_view, typename graph_view_t::vertex_type const  *ptr_d_starting_vertices, gpu_t const  *ptr_d_ranks, size_t num_starting_vertices, std::vector&lt; int &gt; const  &amp;h_fan_out, bool with_replacement=true)'],['../namespacecugraph.html#ab335b5152a7f973af866b6fe347d0e84',1,'cugraph::uniform_nbr_sample(raft::handle_t const  &amp;handle, graph_view_t&lt; vertex_t, edge_t, weight_t, store_transposed, multi_gpu &gt; const  &amp;graph_view, raft::device_span&lt; vertex_t &gt; starting_vertices, raft::host_span&lt; const int &gt; fan_out, bool with_replacement=true, uint64_t seed=0)']]],
  ['uniform_5fselector_5ft_386',['uniform_selector_t',['../structcugraph_1_1detail_1_1original_1_1uniform__selector__t.html',1,'cugraph::detail::original']]],
  ['unrenumber_5fint_5fvertices_387',['unrenumber_int_vertices',['../namespacecugraph.html#a684545dbb07a8981e1b6fcafaa369376',1,'cugraph']]],
  ['unrenumber_5flocal_5fint_5fedges_388',['unrenumber_local_int_edges',['../namespacecugraph.html#a6738df2e950f62bda7fdfbcf0a2ec440',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_srcs, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_dsts, std::vector&lt; size_t &gt; const  &amp;edgelist_edge_counts, vertex_t const  *renumber_map_labels, std::vector&lt; vertex_t &gt; const  &amp;vertex_partition_range_lasts, std::optional&lt; std::vector&lt; std::vector&lt; size_t &gt;&gt;&gt; const  &amp;edgelist_intra_partition_segment_offsets, bool do_expensive_check=false)'],['../namespacecugraph.html#ac18d945222b132c054d2bc748d144872',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, vertex_t *edgelist_srcs, vertex_t *edgelist_dsts, size_t num_edgelist_edges, vertex_t const  *renumber_map_labels, vertex_t num_vertices, bool do_expensive_check=false)']]],
  ['unrenumber_5flocal_5fint_5fvertices_389',['unrenumber_local_int_vertices',['../namespacecugraph.html#ab2d2829de3b33d7f394c8a1ff5169ca5',1,'cugraph']]],
  ['update_5fedge_5fpartition_5fdst_5fproperty_390',['update_edge_partition_dst_property',['../namespacecugraph.html#ab348b4244bd3dfb5c3f62586ed6739b9',1,'cugraph::update_edge_partition_dst_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexPropertyInputIterator vertex_property_input_first, edge_partition_dst_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_dst_property_output, bool do_expensive_check=false)'],['../namespacecugraph.html#a05443da9eb619a6033fcf0de6be9ac5d',1,'cugraph::update_edge_partition_dst_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexIterator vertex_first, VertexIterator vertex_last, VertexPropertyInputIterator vertex_property_input_first, edge_partition_dst_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_dst_property_output, bool do_expensive_check=false)']]],
  ['update_5fedge_5fpartition_5fsrc_5fproperty_391',['update_edge_partition_src_property',['../namespacecugraph.html#afec2d212ed2d658a8f1e88e0b3532282',1,'cugraph::update_edge_partition_src_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexPropertyInputIterator vertex_property_input_first, edge_partition_src_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_src_property_output, bool do_expensive_check=false)'],['../namespacecugraph.html#a18537c53d0b1dea8c2b4487984230916',1,'cugraph::update_edge_partition_src_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexIterator vertex_first, VertexIterator vertex_last, VertexPropertyInputIterator vertex_property_input_first, edge_partition_src_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_src_property_output, bool do_expensive_check=false)']]],
  ['update_5fpaths_392',['update_paths',['../structcugraph_1_1detail_1_1update__paths.html',1,'cugraph::detail']]],
  ['update_5frx_5fmajor_5flocal_5fdegree_5ft_393',['update_rx_major_local_degree_t',['../structcugraph_1_1detail_1_1update__rx__major__local__degree__t.html',1,'cugraph::detail']]],
  ['update_5frx_5fmajor_5flocal_5fnbrs_5ft_394',['update_rx_major_local_nbrs_t',['../structcugraph_1_1detail_1_1update__rx__major__local__nbrs__t.html',1,'cugraph::detail']]],
  ['update_5ftuple_5ffrom_5fvector_5fof_5ftuple_5fscalar_5felements_5fimpl_395',['update_tuple_from_vector_of_tuple_scalar_elements_impl',['../structcugraph_1_1detail_1_1update__tuple__from__vector__of__tuple__scalar__elements__impl.html',1,'cugraph::detail']]],
  ['update_5ftuple_5ffrom_5fvector_5fof_5ftuple_5fscalar_5felements_5fimpl_3c_20tupletype_2c_20i_2c_20i_20_3e_396',['update_tuple_from_vector_of_tuple_scalar_elements_impl&lt; TupleType, I, I &gt;',['../structcugraph_1_1detail_1_1update__tuple__from__vector__of__tuple__scalar__elements__impl_3_01TupleType_00_01I_00_01I_01_4.html',1,'cugraph::detail']]],
  ['update_5fv_5ffrontier_397',['update_v_frontier',['../namespacecugraph.html#ad1970ebead4b3052ea6f1f4e5827d9ec',1,'cugraph::update_v_frontier(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, KeyBuffer &amp;&amp;key_buffer, PayloadBuffer &amp;&amp;payload_buffer, VertexFrontierType &amp;frontier, std::vector&lt; size_t &gt; const &amp;next_frontier_bucket_indices, VertexValueInputIterator vertex_value_input_first, VertexValueOutputIterator vertex_value_output_first, VertexOp v_op, bool do_expensive_check=false)'],['../namespacecugraph.html#ae6aebef0b6d09ca702e5979f29306417',1,'cugraph::update_v_frontier(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, KeyBuffer &amp;&amp;key_buffer, VertexFrontierType &amp;frontier, std::vector&lt; size_t &gt; const &amp;next_frontier_bucket_indices, VertexValueInputIterator vertex_value_input_first, VertexValueOutputIterator vertex_value_output_first, VertexOp v_op, bool do_expensive_check=false)']]],
  ['update_5fv_5ffrontier_5fcall_5fv_5fop_5ft_398',['update_v_frontier_call_v_op_t',['../structcugraph_1_1detail_1_1update__v__frontier__call__v__op__t.html',1,'cugraph::detail']]],
  ['update_5fv_5ffrontier_5fcall_5fv_5fop_5ft_3c_20vertex_5ft_2c_20vertexvalueinputiterator_2c_20vertexvalueoutputiterator_2c_20vertexop_2c_20key_5ft_2c_20void_20_3e_399',['update_v_frontier_call_v_op_t&lt; vertex_t, VertexValueInputIterator, VertexValueOutputIterator, VertexOp, key_t, void &gt;',['../structcugraph_1_1detail_1_1update__v__frontier__call__v__op__t_3_01vertex__t_00_01VertexValueInpc991eb4351f1b215d3bb73296cffaad9.html',1,'cugraph::detail']]],
  ['update_5fvector_5fof_5ftuple_5fscalar_5felements_5ffrom_5ftuple_5fimpl_400',['update_vector_of_tuple_scalar_elements_from_tuple_impl',['../structcugraph_1_1detail_1_1update__vector__of__tuple__scalar__elements__from__tuple__impl.html',1,'cugraph::detail']]],
  ['update_5fvector_5fof_5ftuple_5fscalar_5felements_5ffrom_5ftuple_5fimpl_3c_20tupletype_2c_20i_2c_20i_20_3e_401',['update_vector_of_tuple_scalar_elements_from_tuple_impl&lt; TupleType, I, I &gt;',['../structcugraph_1_1detail_1_1update__vector__of__tuple__scalar__elements__from__tuple__impl_3_01TupleType_00_01I_00_01I_01_4.html',1,'cugraph::detail']]],
  ['updatedevice_402',['updateDevice',['../group__Copy.html#ga18a265a5eb16da13a51f486fe5e3acb7',1,'MLCommon']]],
  ['updatehost_403',['updateHost',['../group__Copy.html#ga9c1498ebc5825f9e63a9de94ced042d5',1,'MLCommon']]]
];
