var searchData=
[
  ['uniform_5fnbr_5fsample_975',['uniform_nbr_sample',['../namespacecugraph.html#ab335b5152a7f973af866b6fe347d0e84',1,'cugraph']]],
  ['uniform_5frandom_5fwalks_976',['uniform_random_walks',['../namespacecugraph.html#a01e9fd9a4aeb36bab7899fb788f44b04',1,'cugraph']]],
  ['unrenumber_5fint_5fvertices_977',['unrenumber_int_vertices',['../namespacecugraph.html#a684545dbb07a8981e1b6fcafaa369376',1,'cugraph']]],
  ['unrenumber_5flocal_5fint_5fedges_978',['unrenumber_local_int_edges',['../namespacecugraph.html#a6738df2e950f62bda7fdfbcf0a2ec440',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_srcs, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_dsts, std::vector&lt; size_t &gt; const  &amp;edgelist_edge_counts, vertex_t const  *renumber_map_labels, std::vector&lt; vertex_t &gt; const  &amp;vertex_partition_range_lasts, std::optional&lt; std::vector&lt; std::vector&lt; size_t &gt;&gt;&gt; const  &amp;edgelist_intra_partition_segment_offsets, bool do_expensive_check=false)'],['../namespacecugraph.html#ac18d945222b132c054d2bc748d144872',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, vertex_t *edgelist_srcs, vertex_t *edgelist_dsts, size_t num_edgelist_edges, vertex_t const  *renumber_map_labels, vertex_t num_vertices, bool do_expensive_check=false)']]],
  ['unrenumber_5flocal_5fint_5fvertices_979',['unrenumber_local_int_vertices',['../namespacecugraph.html#ab2d2829de3b33d7f394c8a1ff5169ca5',1,'cugraph']]],
  ['update_5fedge_5fpartition_5fdst_5fproperty_980',['update_edge_partition_dst_property',['../namespacecugraph.html#ab348b4244bd3dfb5c3f62586ed6739b9',1,'cugraph::update_edge_partition_dst_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexPropertyInputIterator vertex_property_input_first, edge_partition_dst_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_dst_property_output, bool do_expensive_check=false)'],['../namespacecugraph.html#a05443da9eb619a6033fcf0de6be9ac5d',1,'cugraph::update_edge_partition_dst_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexIterator vertex_first, VertexIterator vertex_last, VertexPropertyInputIterator vertex_property_input_first, edge_partition_dst_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_dst_property_output, bool do_expensive_check=false)']]],
  ['update_5fedge_5fpartition_5fsrc_5fproperty_981',['update_edge_partition_src_property',['../namespacecugraph.html#afec2d212ed2d658a8f1e88e0b3532282',1,'cugraph::update_edge_partition_src_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexPropertyInputIterator vertex_property_input_first, edge_partition_src_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_src_property_output, bool do_expensive_check=false)'],['../namespacecugraph.html#a18537c53d0b1dea8c2b4487984230916',1,'cugraph::update_edge_partition_src_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexIterator vertex_first, VertexIterator vertex_last, VertexPropertyInputIterator vertex_property_input_first, edge_partition_src_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_src_property_output, bool do_expensive_check=false)']]],
  ['update_5fv_5ffrontier_982',['update_v_frontier',['../namespacecugraph.html#ad1970ebead4b3052ea6f1f4e5827d9ec',1,'cugraph::update_v_frontier(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, KeyBuffer &amp;&amp;key_buffer, PayloadBuffer &amp;&amp;payload_buffer, VertexFrontierType &amp;frontier, std::vector&lt; size_t &gt; const &amp;next_frontier_bucket_indices, VertexValueInputIterator vertex_value_input_first, VertexValueOutputIterator vertex_value_output_first, VertexOp v_op, bool do_expensive_check=false)'],['../namespacecugraph.html#ae6aebef0b6d09ca702e5979f29306417',1,'cugraph::update_v_frontier(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, KeyBuffer &amp;&amp;key_buffer, VertexFrontierType &amp;frontier, std::vector&lt; size_t &gt; const &amp;next_frontier_bucket_indices, VertexValueInputIterator vertex_value_input_first, VertexValueOutputIterator vertex_value_output_first, VertexOp v_op, bool do_expensive_check=false)']]],
  ['updatedevice_983',['updateDevice',['../group__Copy.html#ga18a265a5eb16da13a51f486fe5e3acb7',1,'MLCommon']]],
  ['updatehost_984',['updateHost',['../group__Copy.html#ga9c1498ebc5825f9e63a9de94ced042d5',1,'MLCommon']]]
];
