var searchData=
[
  ['scalar_785',['scalar',['../structcudf_1_1detail_1_1scalar__factory_1_1scalar.html',1,'cudf::detail::scalar_factory']]],
  ['scalar_5ffactory_786',['scalar_factory',['../structcudf_1_1detail_1_1scalar__factory.html',1,'cudf::detail']]],
  ['scalar_5fscatterer_787',['scalar_scatterer',['../structcudf_1_1detail_1_1scalar__scatterer.html',1,'cudf::detail']]],
  ['schema_5fentry_788',['schema_entry',['../structcudf_1_1io_1_1avro_1_1schema__entry.html',1,'cudf::io::avro']]],
  ['schema_5fparser_789',['schema_parser',['../classcudf_1_1io_1_1avro_1_1schema__parser.html',1,'cudf::io::avro']]],
  ['schemadesc_5fs_790',['schemadesc_s',['../structcudf_1_1io_1_1avro_1_1gpu_1_1schemadesc__s.html',1,'cudf::io::avro::gpu']]],
  ['schemaelement_791',['SchemaElement',['../structcudf_1_1io_1_1parquet_1_1SchemaElement.html',1,'cudf::io::parquet']]],
  ['schematype_792',['SchemaType',['../structcudf_1_1io_1_1orc_1_1SchemaType.html',1,'cudf::io::orc']]],
  ['scoped_5fstream_793',['scoped_stream',['../structcudf_1_1util_1_1cuda_1_1scoped__stream.html',1,'cudf::util::cuda']]],
  ['scratch_5farr_794',['scratch_arr',['../structscratch__arr.html',1,'']]],
  ['segmentedradixsort_795',['SegmentedRadixSort',['../structSegmentedRadixSort.html',1,'']]],
  ['segmentedradixsortplan_796',['SegmentedRadixSortPlan',['../structSegmentedRadixSortPlan.html',1,'']]],
  ['serialtrienode_797',['SerialTrieNode',['../structSerialTrieNode.html',1,'']]],
  ['size_5fof_5fhelper_798',['size_of_helper',['../structcudf_1_1detail_1_1size__of__helper.html',1,'cudf::detail']]],
  ['source_5finfo_799',['source_info',['../structcudf_1_1source__info.html',1,'cudf']]],
  ['standard_5fdeviation_800',['standard_deviation',['../structcudf_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::reduction::op']]],
  ['store_5foutput_5ffunctor_801',['store_output_functor',['../structcudf_1_1detail_1_1store__output__functor.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20columntype_2c_20true_20_3e_802',['store_output_functor&lt; ColumnType, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01ColumnType_00_01true_01_4.html',1,'cudf::detail']]],
  ['stream_803',['Stream',['../structcudf_1_1io_1_1orc_1_1Stream.html',1,'cudf::io::orc']]],
  ['stripefooter_804',['StripeFooter',['../structcudf_1_1io_1_1orc_1_1StripeFooter.html',1,'cudf::io::orc']]],
  ['stripeinformation_805',['StripeInformation',['../structcudf_1_1io_1_1orc_1_1StripeInformation.html',1,'cudf::io::orc']]],
  ['sum_806',['sum',['../structcudf_1_1reduction_1_1op_1_1sum.html',1,'cudf::reduction::op']]],
  ['sum_5fof_5fsquares_807',['sum_of_squares',['../structcudf_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::reduction::op']]]
];
