var searchData=
[
  ['castdateto_5fdispatcher_1458',['CastDateTo_Dispatcher',['../structcudf_1_1detail_1_1CastDateTo__Dispatcher.html',1,'cudf::detail']]],
  ['castfrom_5fdispatcher_1459',['CastFrom_Dispatcher',['../structcudf_1_1detail_1_1CastFrom__Dispatcher.html',1,'cudf::detail']]],
  ['casttimestampto_5fdispatcher_1460',['CastTimestampTo_Dispatcher',['../structcudf_1_1detail_1_1CastTimestampTo__Dispatcher.html',1,'cudf::detail']]],
  ['castto_5fdispatcher_1461',['CastTo_Dispatcher',['../structcudf_1_1detail_1_1CastTo__Dispatcher.html',1,'cudf::detail']]],
  ['characters_5ftokenizer_1462',['characters_tokenizer',['../structnvtext_1_1detail_1_1characters__tokenizer.html',1,'nvtext::detail']]],
  ['check_5ffor_5fnan_1463',['check_for_nan',['../structcudf_1_1experimental_1_1detail_1_1check__for__nan.html',1,'cudf::experimental::detail']]],
  ['cmdlutelement_1464',['CmdLutElement',['../structCmdLutElement.html',1,'']]],
  ['column_1465',['column',['../classcudf_1_1column.html',1,'cudf']]],
  ['column_5fbuffer_1466',['column_buffer',['../structcudf_1_1experimental_1_1io_1_1detail_1_1column__buffer.html',1,'cudf::experimental::io::detail']]],
  ['column_5fdesc_1467',['column_desc',['../structcudf_1_1io_1_1avro_1_1column__desc.html',1,'cudf::io::avro']]],
  ['column_5fdevice_5fview_1468',['column_device_view',['../classcudf_1_1column__device__view.html',1,'cudf']]],
  ['column_5fdevice_5fview_5fbase_1469',['column_device_view_base',['../classcudf_1_1detail_1_1column__device__view__base.html',1,'cudf::detail']]],
  ['column_5fgatherer_1470',['column_gatherer',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer.html',1,'cudf::experimental::detail::column_gatherer'],['../structcudf_1_1detail_1_1column__gatherer.html',1,'cudf::detail::column_gatherer']]],
  ['column_5fgatherer_5fimpl_1471',['column_gatherer_impl',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer__impl.html',1,'cudf::experimental::detail']]],
  ['column_5fgatherer_5fimpl_3c_20dictionary32_2c_20mapittype_20_3e_1472',['column_gatherer_impl&lt; dictionary32, MapItType &gt;',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer__impl_3_01dictionary32_00_01MapItType_01_4.html',1,'cudf::experimental::detail']]],
  ['column_5fgatherer_5fimpl_3c_20string_5fview_2c_20mapittype_20_3e_1473',['column_gatherer_impl&lt; string_view, MapItType &gt;',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer__impl_3_01string__view_00_01MapItType_01_4.html',1,'cudf::experimental::detail']]],
  ['column_5fmerger_1474',['column_merger',['../structcudf_1_1experimental_1_1detail_1_1column__merger.html',1,'cudf::experimental::detail']]],
  ['column_5frange_1475',['column_range',['../structcudf_1_1detail_1_1column__range__factory_1_1column__range.html',1,'cudf::detail::column_range_factory']]],
  ['column_5frange_5ffactory_1476',['column_range_factory',['../structcudf_1_1detail_1_1column__range__factory.html',1,'cudf::detail']]],
  ['column_5fscatterer_1477',['column_scatterer',['../structcudf_1_1experimental_1_1detail_1_1column__scatterer.html',1,'cudf::experimental::detail']]],
  ['column_5fto_5fstrings_5ffn_1478',['column_to_strings_fn',['../structcolumn__to__strings__fn.html',1,'']]],
  ['column_5fview_1479',['column_view',['../classcudf_1_1column__view.html',1,'cudf']]],
  ['column_5fview_5fbase_1480',['column_view_base',['../classcudf_1_1detail_1_1column__view__base.html',1,'cudf::detail']]],
  ['columnchunk_1481',['ColumnChunk',['../structcudf_1_1io_1_1parquet_1_1ColumnChunk.html',1,'cudf::io::parquet']]],
  ['columnchunkdesc_1482',['ColumnChunkDesc',['../structcudf_1_1io_1_1parquet_1_1gpu_1_1ColumnChunkDesc.html',1,'cudf::io::parquet::gpu']]],
  ['columndesc_1483',['ColumnDesc',['../structcudf_1_1io_1_1orc_1_1gpu_1_1ColumnDesc.html',1,'cudf::io::orc::gpu']]],
  ['columnencoding_1484',['ColumnEncoding',['../structcudf_1_1io_1_1orc_1_1ColumnEncoding.html',1,'cudf::io::orc']]],
  ['columninfo_1485',['ColumnInfo',['../structcudf_1_1experimental_1_1io_1_1json_1_1ColumnInfo.html',1,'cudf::experimental::io::json::ColumnInfo'],['../structcudf_1_1io_1_1json_1_1ColumnInfo.html',1,'cudf::io::json::ColumnInfo']]],
  ['columnmetadata_1486',['ColumnMetaData',['../structcudf_1_1io_1_1parquet_1_1ColumnMetaData.html',1,'cudf::io::parquet']]],
  ['compactprotocolreader_1487',['CompactProtocolReader',['../classcudf_1_1io_1_1parquet_1_1CompactProtocolReader.html',1,'cudf::io::parquet']]],
  ['compactprotocolwriter_1488',['CompactProtocolWriter',['../classcudf_1_1io_1_1parquet_1_1CompactProtocolWriter.html',1,'cudf::io::parquet']]],
  ['compare_5fwith_5fvalue_1489',['compare_with_value',['../structcudf_1_1detail_1_1compare__with__value.html',1,'cudf::detail']]],
  ['compound_5fop_1490',['compound_op',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compound_5fop_3c_20mean_20_3e_1491',['compound_op&lt; mean &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compound_5fop_3c_20standard_5fdeviation_20_3e_1492',['compound_op&lt; standard_deviation &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compound_5fop_3c_20variance_20_3e_1493',['compound_op&lt; variance &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compressed_5fstream_5fs_1494',['compressed_stream_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1compressed__stream__s.html',1,'cudf::io::orc::gpu']]],
  ['compressedstreaminfo_1495',['CompressedStreamInfo',['../structcudf_1_1io_1_1orc_1_1gpu_1_1CompressedStreamInfo.html',1,'cudf::io::orc::gpu']]],
  ['compute_5fsingle_5fpass_5faggs_1496',['compute_single_pass_aggs',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1hash_1_1compute__single__pass__aggs.html',1,'cudf::experimental::groupby::detail::hash']]],
  ['compute_5fsort_5fjoin_1497',['compute_sort_join',['../structcompute__sort__join.html',1,'']]],
  ['concurrent_5funordered_5fmap_1498',['concurrent_unordered_map',['../classconcurrent__unordered__map.html',1,'']]],
  ['concurrent_5funordered_5fmultimap_1499',['concurrent_unordered_multimap',['../classconcurrent__unordered__multimap.html',1,'']]],
  ['const_5fiterator_1500',['const_iterator',['../classcudf_1_1string__view_1_1const__iterator.html',1,'cudf::string_view']]],
  ['container_1501',['container',['../classcudf_1_1io_1_1avro_1_1container.html',1,'cudf::io::avro']]],
  ['contains_5fscalar_5fdispatch_1502',['contains_scalar_dispatch',['../structcudf_1_1experimental_1_1contains__scalar__dispatch.html',1,'cudf::experimental']]],
  ['contents_1503',['contents',['../structcudf_1_1column_1_1contents.html',1,'cudf::column']]],
  ['contiguous_5fsplit_5frecord_5fresult_1504',['contiguous_split_record_result',['../structcudf_1_1strings_1_1contiguous__split__record__result.html',1,'cudf::strings']]],
  ['contiguous_5fsplit_5fresult_1505',['contiguous_split_result',['../structcudf_1_1experimental_1_1contiguous__split__result.html',1,'cudf::experimental']]],
  ['convertfunctor_1506',['ConvertFunctor',['../structcudf_1_1io_1_1csv_1_1gpu_1_1ConvertFunctor.html',1,'cudf::io::csv::gpu::ConvertFunctor'],['../structcudf_1_1io_1_1json_1_1ConvertFunctor.html',1,'cudf::io::json::ConvertFunctor']]],
  ['corresponding_5ffunctor_1507',['corresponding_functor',['../structcudf_1_1groupby_1_1corresponding__functor.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20count_20_3e_1508',['corresponding_functor&lt; COUNT &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01COUNT_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20max_20_3e_1509',['corresponding_functor&lt; MAX &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01MAX_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20min_20_3e_1510',['corresponding_functor&lt; MIN &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01MIN_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20sum_20_3e_1511',['corresponding_functor&lt; SUM &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01SUM_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5foperator_1512',['corresponding_operator',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3aall_20_3e_1513',['corresponding_operator&lt; aggregation::ALL &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1ALL_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3aany_20_3e_1514',['corresponding_operator&lt; aggregation::ANY &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1ANY_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3acount_5fall_20_3e_1515',['corresponding_operator&lt; aggregation::COUNT_ALL &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1COUNT__ALL_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3acount_5fvalid_20_3e_1516',['corresponding_operator&lt; aggregation::COUNT_VALID &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1COUNT__VALID_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3amax_20_3e_1517',['corresponding_operator&lt; aggregation::MAX &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1MAX_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3amin_20_3e_1518',['corresponding_operator&lt; aggregation::MIN &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1MIN_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3aproduct_20_3e_1519',['corresponding_operator&lt; aggregation::PRODUCT &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1PRODUCT_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3asum_20_3e_1520',['corresponding_operator&lt; aggregation::SUM &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1SUM_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3asum_5fof_5fsquares_20_3e_1521',['corresponding_operator&lt; aggregation::SUM_OF_SQUARES &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1SUM__OF__SQUARES_01_4.html',1,'cudf::experimental::detail']]],
  ['create_5fcolumn_5ffrom_5fview_1522',['create_column_from_view',['../structcudf_1_1create__column__from__view.html',1,'cudf']]],
  ['create_5fcolumn_5ffrom_5fview_5fvector_1523',['create_column_from_view_vector',['../structcudf_1_1create__column__from__view__vector.html',1,'cudf']]],
  ['csr_5fgdf_5f_1524',['csr_gdf_',['../structcsr__gdf__.html',1,'']]],
  ['csv_5fread_5farg_1525',['csv_read_arg',['../structcudf_1_1csv__read__arg.html',1,'cudf']]],
  ['csv_5fwrite_5farg_1526',['csv_write_arg',['../structcsv__write__arg.html',1,'']]],
  ['cuda_5ferror_1527',['cuda_error',['../structcudf_1_1cuda__error.html',1,'cudf']]],
  ['cudamessagereader_1528',['CudaMessageReader',['../classCudaMessageReader.html',1,'']]],
  ['cudfjitcache_1529',['cudfJitCache',['../classcudf_1_1jit_1_1cudfJitCache.html',1,'cudf::jit']]],
  ['cycle_5fiterator_5fadapter_1530',['cycle_iterator_adapter',['../classcycle__iterator__adapter.html',1,'']]]
];
