var searchData=
[
  ['castdateto_5fdispatcher_1533',['CastDateTo_Dispatcher',['../structcudf_1_1detail_1_1CastDateTo__Dispatcher.html',1,'cudf::detail']]],
  ['castfrom_5fdispatcher_1534',['CastFrom_Dispatcher',['../structcudf_1_1detail_1_1CastFrom__Dispatcher.html',1,'cudf::detail']]],
  ['casttimestampto_5fdispatcher_1535',['CastTimestampTo_Dispatcher',['../structcudf_1_1detail_1_1CastTimestampTo__Dispatcher.html',1,'cudf::detail']]],
  ['castto_5fdispatcher_1536',['CastTo_Dispatcher',['../structcudf_1_1detail_1_1CastTo__Dispatcher.html',1,'cudf::detail']]],
  ['category_1537',['category',['../classnvtx3_1_1category.html',1,'nvtx3']]],
  ['characters_5ftokenizer_1538',['characters_tokenizer',['../structnvtext_1_1detail_1_1characters__tokenizer.html',1,'nvtext::detail']]],
  ['check_5ffor_5fnan_1539',['check_for_nan',['../structcudf_1_1experimental_1_1detail_1_1check__for__nan.html',1,'cudf::experimental::detail']]],
  ['cmdlutelement_1540',['CmdLutElement',['../structCmdLutElement.html',1,'']]],
  ['color_1541',['color',['../classnvtx3_1_1color.html',1,'nvtx3']]],
  ['column_1542',['column',['../classcudf_1_1column.html',1,'cudf']]],
  ['column_5fbuffer_1543',['column_buffer',['../structcudf_1_1experimental_1_1io_1_1detail_1_1column__buffer.html',1,'cudf::experimental::io::detail']]],
  ['column_5fdesc_1544',['column_desc',['../structcudf_1_1io_1_1avro_1_1column__desc.html',1,'cudf::io::avro']]],
  ['column_5fdevice_5fview_1545',['column_device_view',['../classcudf_1_1column__device__view.html',1,'cudf']]],
  ['column_5fdevice_5fview_5fbase_1546',['column_device_view_base',['../classcudf_1_1detail_1_1column__device__view__base.html',1,'cudf::detail']]],
  ['column_5ffrom_5fscalar_5fdispatch_1547',['column_from_scalar_dispatch',['../structcudf_1_1column__from__scalar__dispatch.html',1,'cudf']]],
  ['column_5fgatherer_1548',['column_gatherer',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer.html',1,'cudf::experimental::detail::column_gatherer'],['../structcudf_1_1detail_1_1column__gatherer.html',1,'cudf::detail::column_gatherer']]],
  ['column_5fgatherer_5fimpl_1549',['column_gatherer_impl',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer__impl.html',1,'cudf::experimental::detail']]],
  ['column_5fgatherer_5fimpl_3c_20dictionary32_2c_20mapittype_20_3e_1550',['column_gatherer_impl&lt; dictionary32, MapItType &gt;',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer__impl_3_01dictionary32_00_01MapItType_01_4.html',1,'cudf::experimental::detail']]],
  ['column_5fgatherer_5fimpl_3c_20string_5fview_2c_20mapittype_20_3e_1551',['column_gatherer_impl&lt; string_view, MapItType &gt;',['../structcudf_1_1experimental_1_1detail_1_1column__gatherer__impl_3_01string__view_00_01MapItType_01_4.html',1,'cudf::experimental::detail']]],
  ['column_5fmerger_1552',['column_merger',['../structcudf_1_1experimental_1_1detail_1_1column__merger.html',1,'cudf::experimental::detail']]],
  ['column_5frange_1553',['column_range',['../structcudf_1_1detail_1_1column__range__factory_1_1column__range.html',1,'cudf::detail::column_range_factory']]],
  ['column_5frange_5ffactory_1554',['column_range_factory',['../structcudf_1_1detail_1_1column__range__factory.html',1,'cudf::detail']]],
  ['column_5fscatterer_1555',['column_scatterer',['../structcudf_1_1experimental_1_1detail_1_1column__scatterer.html',1,'cudf::experimental::detail']]],
  ['column_5fscatterer_5fimpl_1556',['column_scatterer_impl',['../structcudf_1_1experimental_1_1detail_1_1column__scatterer__impl.html',1,'cudf::experimental::detail']]],
  ['column_5fscatterer_5fimpl_3c_20dictionary32_2c_20mapiterator_20_3e_1557',['column_scatterer_impl&lt; dictionary32, MapIterator &gt;',['../structcudf_1_1experimental_1_1detail_1_1column__scatterer__impl_3_01dictionary32_00_01MapIterator_01_4.html',1,'cudf::experimental::detail']]],
  ['column_5fscatterer_5fimpl_3c_20string_5fview_2c_20mapiterator_20_3e_1558',['column_scatterer_impl&lt; string_view, MapIterator &gt;',['../structcudf_1_1experimental_1_1detail_1_1column__scatterer__impl_3_01string__view_00_01MapIterator_01_4.html',1,'cudf::experimental::detail']]],
  ['column_5fto_5fstrings_5ffn_1559',['column_to_strings_fn',['../structcolumn__to__strings__fn.html',1,'']]],
  ['column_5fview_1560',['column_view',['../classcudf_1_1column__view.html',1,'cudf']]],
  ['column_5fview_5fbase_1561',['column_view_base',['../classcudf_1_1detail_1_1column__view__base.html',1,'cudf::detail']]],
  ['columnchunk_1562',['ColumnChunk',['../structcudf_1_1io_1_1parquet_1_1ColumnChunk.html',1,'cudf::io::parquet']]],
  ['columnchunkdesc_1563',['ColumnChunkDesc',['../structcudf_1_1io_1_1parquet_1_1gpu_1_1ColumnChunkDesc.html',1,'cudf::io::parquet::gpu']]],
  ['columndesc_1564',['ColumnDesc',['../structcudf_1_1io_1_1orc_1_1gpu_1_1ColumnDesc.html',1,'cudf::io::orc::gpu']]],
  ['columnencoding_1565',['ColumnEncoding',['../structcudf_1_1io_1_1orc_1_1ColumnEncoding.html',1,'cudf::io::orc']]],
  ['columninfo_1566',['ColumnInfo',['../structcudf_1_1experimental_1_1io_1_1json_1_1ColumnInfo.html',1,'cudf::experimental::io::json::ColumnInfo'],['../structcudf_1_1io_1_1json_1_1ColumnInfo.html',1,'cudf::io::json::ColumnInfo']]],
  ['columnmetadata_1567',['ColumnMetaData',['../structcudf_1_1io_1_1parquet_1_1ColumnMetaData.html',1,'cudf::io::parquet']]],
  ['compactprotocolreader_1568',['CompactProtocolReader',['../classcudf_1_1io_1_1parquet_1_1CompactProtocolReader.html',1,'cudf::io::parquet']]],
  ['compactprotocolwriter_1569',['CompactProtocolWriter',['../classcudf_1_1io_1_1parquet_1_1CompactProtocolWriter.html',1,'cudf::io::parquet']]],
  ['compare_5fwith_5fvalue_1570',['compare_with_value',['../structcudf_1_1detail_1_1compare__with__value.html',1,'cudf::detail']]],
  ['compound_5fop_1571',['compound_op',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compound_5fop_3c_20mean_20_3e_1572',['compound_op&lt; mean &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compound_5fop_3c_20standard_5fdeviation_20_3e_1573',['compound_op&lt; standard_deviation &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compound_5fop_3c_20variance_20_3e_1574',['compound_op&lt; variance &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1compound__op.html',1,'cudf::experimental::reduction::op']]],
  ['compressed_5fstream_5fs_1575',['compressed_stream_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1compressed__stream__s.html',1,'cudf::io::orc::gpu']]],
  ['compressedstreaminfo_1576',['CompressedStreamInfo',['../structcudf_1_1io_1_1orc_1_1gpu_1_1CompressedStreamInfo.html',1,'cudf::io::orc::gpu']]],
  ['compute_5fsingle_5fpass_5faggs_1577',['compute_single_pass_aggs',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1hash_1_1compute__single__pass__aggs.html',1,'cudf::experimental::groupby::detail::hash']]],
  ['compute_5fsort_5fjoin_1578',['compute_sort_join',['../structcompute__sort__join.html',1,'']]],
  ['concurrent_5funordered_5fmap_1579',['concurrent_unordered_map',['../classconcurrent__unordered__map.html',1,'']]],
  ['concurrent_5funordered_5fmultimap_1580',['concurrent_unordered_multimap',['../classconcurrent__unordered__multimap.html',1,'']]],
  ['const_5fiterator_1581',['const_iterator',['../classcudf_1_1string__view_1_1const__iterator.html',1,'cudf::string_view']]],
  ['container_1582',['container',['../classcudf_1_1io_1_1avro_1_1container.html',1,'cudf::io::avro']]],
  ['contents_1583',['contents',['../structcudf_1_1column_1_1contents.html',1,'cudf::column']]],
  ['contiguous_5fsplit_5frecord_5fresult_1584',['contiguous_split_record_result',['../structcudf_1_1strings_1_1contiguous__split__record__result.html',1,'cudf::strings']]],
  ['contiguous_5fsplit_5fresult_1585',['contiguous_split_result',['../structcudf_1_1experimental_1_1contiguous__split__result.html',1,'cudf::experimental']]],
  ['convertfunctor_1586',['ConvertFunctor',['../structcudf_1_1io_1_1csv_1_1gpu_1_1ConvertFunctor.html',1,'cudf::io::csv::gpu::ConvertFunctor'],['../structcudf_1_1io_1_1json_1_1ConvertFunctor.html',1,'cudf::io::json::ConvertFunctor']]],
  ['corresponding_5ffunctor_1587',['corresponding_functor',['../structcudf_1_1groupby_1_1corresponding__functor.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20count_20_3e_1588',['corresponding_functor&lt; COUNT &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01COUNT_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20max_20_3e_1589',['corresponding_functor&lt; MAX &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01MAX_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20min_20_3e_1590',['corresponding_functor&lt; MIN &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01MIN_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5ffunctor_3c_20sum_20_3e_1591',['corresponding_functor&lt; SUM &gt;',['../structcudf_1_1groupby_1_1corresponding__functor_3_01SUM_01_4.html',1,'cudf::groupby']]],
  ['corresponding_5foperator_1592',['corresponding_operator',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3aall_20_3e_1593',['corresponding_operator&lt; aggregation::ALL &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1ALL_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3aany_20_3e_1594',['corresponding_operator&lt; aggregation::ANY &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1ANY_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3acount_5fall_20_3e_1595',['corresponding_operator&lt; aggregation::COUNT_ALL &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1COUNT__ALL_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3acount_5fvalid_20_3e_1596',['corresponding_operator&lt; aggregation::COUNT_VALID &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1COUNT__VALID_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3amax_20_3e_1597',['corresponding_operator&lt; aggregation::MAX &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1MAX_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3amin_20_3e_1598',['corresponding_operator&lt; aggregation::MIN &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1MIN_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3aproduct_20_3e_1599',['corresponding_operator&lt; aggregation::PRODUCT &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1PRODUCT_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3asum_20_3e_1600',['corresponding_operator&lt; aggregation::SUM &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1SUM_01_4.html',1,'cudf::experimental::detail']]],
  ['corresponding_5foperator_3c_20aggregation_3a_3asum_5fof_5fsquares_20_3e_1601',['corresponding_operator&lt; aggregation::SUM_OF_SQUARES &gt;',['../structcudf_1_1experimental_1_1detail_1_1corresponding__operator_3_01aggregation_1_1SUM__OF__SQUARES_01_4.html',1,'cudf::experimental::detail']]],
  ['csr_5fgdf_5f_1602',['csr_gdf_',['../structcsr__gdf__.html',1,'']]],
  ['csv_5fread_5farg_1603',['csv_read_arg',['../structcudf_1_1csv__read__arg.html',1,'cudf']]],
  ['csv_5fwrite_5farg_1604',['csv_write_arg',['../structcsv__write__arg.html',1,'']]],
  ['cuda_5ferror_1605',['cuda_error',['../structcudf_1_1cuda__error.html',1,'cudf']]],
  ['cudamessagereader_1606',['CudaMessageReader',['../classCudaMessageReader.html',1,'']]],
  ['cudfjitcache_1607',['cudfJitCache',['../classcudf_1_1jit_1_1cudfJitCache.html',1,'cudf::jit']]],
  ['cycle_5fiterator_5fadapter_1608',['cycle_iterator_adapter',['../classcycle__iterator__adapter.html',1,'']]]
];
