var searchData=
[
  ['scalar_1926',['scalar',['../structcudf_1_1detail_1_1scalar__factory_1_1scalar.html',1,'cudf::detail::scalar_factory::scalar&lt; T &gt;'],['../classcudf_1_1scalar.html',1,'cudf::scalar']]],
  ['scalar_5fdevice_5fview_5fbase_1927',['scalar_device_view_base',['../classcudf_1_1detail_1_1scalar__device__view__base.html',1,'cudf::detail']]],
  ['scalar_5ffactory_1928',['scalar_factory',['../structcudf_1_1detail_1_1scalar__factory.html',1,'cudf::detail']]],
  ['scalar_5fscatterer_1929',['scalar_scatterer',['../structcudf_1_1detail_1_1scalar__scatterer.html',1,'cudf::detail']]],
  ['scaled_5finteger_1930',['scaled_integer',['../structnumeric_1_1scaled__integer.html',1,'numeric']]],
  ['scandispatcher_1931',['ScanDispatcher',['../structcudf_1_1experimental_1_1detail_1_1ScanDispatcher.html',1,'cudf::experimental::detail']]],
  ['schema_5fentry_1932',['schema_entry',['../structcudf_1_1io_1_1avro_1_1schema__entry.html',1,'cudf::io::avro']]],
  ['schema_5fparser_1933',['schema_parser',['../classcudf_1_1io_1_1avro_1_1schema__parser.html',1,'cudf::io::avro']]],
  ['schemadesc_5fs_1934',['schemadesc_s',['../structcudf_1_1io_1_1avro_1_1gpu_1_1schemadesc__s.html',1,'cudf::io::avro::gpu']]],
  ['schemaelement_1935',['SchemaElement',['../structcudf_1_1io_1_1parquet_1_1SchemaElement.html',1,'cudf::io::parquet']]],
  ['schematype_1936',['SchemaType',['../structcudf_1_1io_1_1orc_1_1SchemaType.html',1,'cudf::io::orc']]],
  ['scoped_5fstream_1937',['scoped_stream',['../structcudf_1_1util_1_1cuda_1_1scoped__stream.html',1,'cudf::util::cuda']]],
  ['scratch_5farr_1938',['scratch_arr',['../structcudf_1_1io_1_1scratch__arr.html',1,'cudf::io']]],
  ['serialtrienode_1939',['SerialTrieNode',['../structSerialTrieNode.html',1,'']]],
  ['simple_5fop_1940',['simple_op',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20max_20_3e_1941',['simple_op&lt; max &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20mean_20_3e_1942',['simple_op&lt; mean &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20min_20_3e_1943',['simple_op&lt; min &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20product_20_3e_1944',['simple_op&lt; product &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20standard_5fdeviation_20_3e_1945',['simple_op&lt; standard_deviation &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20sum_20_3e_1946',['simple_op&lt; sum &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20sum_5fof_5fsquares_20_3e_1947',['simple_op&lt; sum_of_squares &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20variance_20_3e_1948',['simple_op&lt; variance &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['sink_5finfo_1949',['sink_info',['../structcudf_1_1sink__info.html',1,'cudf::sink_info'],['../structcudf_1_1experimental_1_1io_1_1sink__info.html',1,'cudf::experimental::io::sink_info']]],
  ['size_5fof_5fhelper_1950',['size_of_helper',['../structcudf_1_1detail_1_1size__of__helper.html',1,'cudf::detail']]],
  ['snap_5fstate_5fs_1951',['snap_state_s',['../structcudf_1_1io_1_1snap__state__s.html',1,'cudf::io']]],
  ['sort_5fgroupby_5fhelper_1952',['sort_groupby_helper',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1sort_1_1sort__groupby__helper.html',1,'cudf::experimental::groupby::detail::sort']]],
  ['source_5finfo_1953',['source_info',['../structcudf_1_1source__info.html',1,'cudf::source_info'],['../structcudf_1_1experimental_1_1io_1_1source__info.html',1,'cudf::experimental::io::source_info']]],
  ['standard_5fdeviation_1954',['standard_deviation',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::experimental::reduction::op::standard_deviation'],['../structcudf_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::reduction::op::standard_deviation']]],
  ['statistics_5fchunk_1955',['statistics_chunk',['../structcudf_1_1io_1_1statistics__chunk.html',1,'cudf::io']]],
  ['statistics_5fgroup_1956',['statistics_group',['../structcudf_1_1io_1_1statistics__group.html',1,'cudf::io']]],
  ['statistics_5fmerge_5fgroup_1957',['statistics_merge_group',['../structcudf_1_1io_1_1statistics__merge__group.html',1,'cudf::io']]],
  ['statistics_5fval_1958',['statistics_val',['../unioncudf_1_1io_1_1statistics__val.html',1,'cudf::io']]],
  ['stats_1959',['stats',['../structcudf_1_1io_1_1csv_1_1column__parse_1_1stats.html',1,'cudf::io::csv::column_parse']]],
  ['stats_5fcolumn_5fdesc_1960',['stats_column_desc',['../structcudf_1_1io_1_1stats__column__desc.html',1,'cudf::io']]],
  ['stats_5fstate_5fs_1961',['stats_state_s',['../structcudf_1_1io_1_1stats__state__s.html',1,'cudf::io::stats_state_s'],['../structcudf_1_1io_1_1orc_1_1gpu_1_1stats__state__s.html',1,'cudf::io::orc::gpu::stats_state_s']]],
  ['std_5fargs_1962',['std_args',['../structcudf_1_1groupby_1_1sort_1_1std__args.html',1,'cudf::groupby::sort']]],
  ['std_5fvar_5faggregation_1963',['std_var_aggregation',['../structcudf_1_1experimental_1_1detail_1_1std__var__aggregation.html',1,'cudf::experimental::detail']]],
  ['store_5foutput_5ffunctor_1964',['store_output_functor',['../structcudf_1_1detail_1_1store__output__functor.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20_5ft_2c_20true_20_3e_1965',['store_output_functor&lt; _T, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01__T_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20columntype_2c_20true_20_3e_1966',['store_output_functor&lt; ColumnType, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01ColumnType_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5fresult_5ffunctor_1967',['store_result_functor',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1store__result__functor.html',1,'cudf::experimental::groupby::detail']]],
  ['strdata_5fenc_5fstate_5fs_1968',['strdata_enc_state_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1strdata__enc__state__s.html',1,'cudf::io::orc::gpu']]],
  ['stream_1969',['Stream',['../structcudf_1_1io_1_1orc_1_1Stream.html',1,'cudf::io::orc']]],
  ['string_5fscalar_1970',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fscalar_5fdevice_5fview_1971',['string_scalar_device_view',['../classcudf_1_1string__scalar__device__view.html',1,'cudf']]],
  ['string_5fstats_1972',['string_stats',['../structcudf_1_1io_1_1string__stats.html',1,'cudf::io']]],
  ['string_5fview_1973',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['string_5fview_5fto_5fpair_1974',['string_view_to_pair',['../structcudf_1_1string__view__to__pair.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_1975',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['strings_5ftokenizer_1976',['strings_tokenizer',['../structnvtext_1_1detail_1_1strings__tokenizer.html',1,'nvtext::detail']]],
  ['stringsstatistics_1977',['StringsStatistics',['../structStringsStatistics.html',1,'']]],
  ['stripedictionary_1978',['StripeDictionary',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeDictionary.html',1,'cudf::io::orc::gpu']]],
  ['stripefooter_1979',['StripeFooter',['../structcudf_1_1io_1_1orc_1_1StripeFooter.html',1,'cudf::io::orc']]],
  ['stripeinformation_1980',['StripeInformation',['../structcudf_1_1io_1_1orc_1_1StripeInformation.html',1,'cudf::io::orc']]],
  ['stripestatistics_1981',['StripeStatistics',['../structcudf_1_1io_1_1orc_1_1StripeStatistics.html',1,'cudf::io::orc']]],
  ['stripestream_1982',['StripeStream',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeStream.html',1,'cudf::io::orc::gpu']]],
  ['strong_5ftypedef_1983',['strong_typedef',['../structnumeric_1_1strong__typedef.html',1,'numeric']]],
  ['strong_5ftypedef_3c_20int32_5ft_20_3e_1984',['strong_typedef&lt; int32_t &gt;',['../structnumeric_1_1strong__typedef.html',1,'numeric']]],
  ['sum_1985',['sum',['../structcudf_1_1reduction_1_1op_1_1sum.html',1,'cudf::reduction::op::sum'],['../structcudf_1_1experimental_1_1reduction_1_1op_1_1sum.html',1,'cudf::experimental::reduction::op::sum']]],
  ['sum_5fof_5fsquares_1986',['sum_of_squares',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::experimental::reduction::op::sum_of_squares'],['../structcudf_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::reduction::op::sum_of_squares']]]
];
