var searchData=
[
  ['scalar_2052',['scalar',['../classcudf_1_1scalar.html',1,'cudf']]],
  ['scalar_5fdevice_5fview_5fbase_2053',['scalar_device_view_base',['../classcudf_1_1detail_1_1scalar__device__view__base.html',1,'cudf::detail']]],
  ['scaled_5finteger_2054',['scaled_integer',['../structnumeric_1_1scaled__integer.html',1,'numeric']]],
  ['scan_5faggregation_2055',['scan_aggregation',['../classcudf_1_1scan__aggregation.html',1,'cudf']]],
  ['scan_5frequest_2056',['scan_request',['../structcudf_1_1groupby_1_1scan__request.html',1,'cudf::groupby']]],
  ['segmented_5freduce_5faggregation_2057',['segmented_reduce_aggregation',['../classcudf_1_1segmented__reduce__aggregation.html',1,'cudf']]],
  ['self_5fcomparator_2058',['self_comparator',['../classcudf_1_1experimental_1_1row_1_1lexicographic_1_1self__comparator.html',1,'cudf::experimental::row::lexicographic::self_comparator'],['../classcudf_1_1experimental_1_1row_1_1equality_1_1self__comparator.html',1,'cudf::experimental::row::equality::self_comparator']]],
  ['sink_5finfo_2059',['sink_info',['../structcudf_1_1io_1_1sink__info.html',1,'cudf::io']]],
  ['sorting_5fphysical_5felement_5fcomparator_2060',['sorting_physical_element_comparator',['../structcudf_1_1experimental_1_1row_1_1lexicographic_1_1sorting__physical__element__comparator.html',1,'cudf::experimental::row::lexicographic']]],
  ['source_5finfo_2061',['source_info',['../structcudf_1_1io_1_1source__info.html',1,'cudf::io']]],
  ['span_5fbase_2062',['span_base',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20t_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20t_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_2063',['span_base&lt; T, cudf::dynamic_extent, device_span&lt; T, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20t_2c_20cudf_3a_3adynamic_5fextent_2c_20host_5fspan_3c_20t_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_2064',['span_base&lt; T, cudf::dynamic_extent, host_span&lt; T, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['stack_5ftrace_2065',['stack_trace',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1detail_1_1stack__trace.html',1,'rmm::detail']]],
  ['statistics_5fresource_5fadaptor_2066',['statistics_resource_adaptor',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1mr_1_1statistics__resource__adaptor.html',1,'rmm::mr']]],
  ['stream_5fallocator_5fadaptor_2067',['stream_allocator_adaptor',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1mr_1_1stream__allocator__adaptor.html',1,'rmm::mr']]],
  ['stream_5fevent_5fpair_2068',['stream_event_pair',['https://docs.rapids.ai/api/librmm/22.08/structrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource_1_1stream__event__pair.html',1,'rmm::mr::detail::stream_ordered_memory_resource']]],
  ['stream_5fordered_5fmemory_5fresource_2069',['stream_ordered_memory_resource',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource.html',1,'rmm::mr::detail']]],
  ['stream_5fordered_5fmemory_5fresource_3c_20fixed_5fsize_5fmemory_5fresource_3c_20upstream_20_3e_2c_20detail_3a_3afixed_5fsize_5ffree_5flist_20_3e_2070',['stream_ordered_memory_resource&lt; fixed_size_memory_resource&lt; Upstream &gt;, detail::fixed_size_free_list &gt;',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource.html',1,'']]],
  ['stream_5fordered_5fmemory_5fresource_3c_20pool_5fmemory_5fresource_3c_20upstream_20_3e_2c_20detail_3a_3acoalescing_5ffree_5flist_20_3e_2071',['stream_ordered_memory_resource&lt; pool_memory_resource&lt; Upstream &gt;, detail::coalescing_free_list &gt;',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource.html',1,'']]],
  ['string_5fscalar_2072',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fscalar_5fdevice_5fview_2073',['string_scalar_device_view',['../classcudf_1_1string__scalar__device__view.html',1,'cudf']]],
  ['string_5fstatistics_2074',['string_statistics',['../structcudf_1_1io_1_1string__statistics.html',1,'cudf::io']]],
  ['string_5fview_2075',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_2076',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['strings_5fcolumn_5fwrapper_2077',['strings_column_wrapper',['../classcudf_1_1test_1_1strings__column__wrapper.html',1,'cudf::test']]],
  ['strong_5findex_5fiterator_2078',['strong_index_iterator',['../structcudf_1_1experimental_1_1row_1_1strong__index__iterator.html',1,'cudf::experimental::row']]],
  ['struct_5fscalar_2079',['struct_scalar',['../classcudf_1_1struct__scalar.html',1,'cudf']]],
  ['struct_5fview_2080',['struct_view',['../classcudf_1_1struct__view.html',1,'cudf']]],
  ['structs_5fcolumn_5fdevice_5fview_2081',['structs_column_device_view',['../classcudf_1_1detail_1_1structs__column__device__view.html',1,'cudf::detail']]],
  ['structs_5fcolumn_5fview_2082',['structs_column_view',['../classcudf_1_1structs__column__view.html',1,'cudf']]],
  ['structs_5fcolumn_5fwrapper_2083',['structs_column_wrapper',['../classcudf_1_1test_1_1structs__column__wrapper.html',1,'cudf::test']]],
  ['sum_5fstatistics_2084',['sum_statistics',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20double_20_3e_2085',['sum_statistics&lt; double &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20int64_5ft_20_3e_2086',['sum_statistics&lt; int64_t &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20std_3a_3astring_20_3e_2087',['sum_statistics&lt; std::string &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20uint64_5ft_20_3e_2088',['sum_statistics&lt; uint64_t &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['superblock_2089',['superblock',['https://docs.rapids.ai/api/librmm/22.08/classrmm_1_1mr_1_1detail_1_1arena_1_1superblock.html',1,'rmm::mr::detail::arena']]]
];
