var searchData=
[
  ['uniform_5fnbr_5fsample_841',['uniform_nbr_sample',['../namespacecugraph.html#a8ff43a61abf7eb1ae79d364b2d7cebb1',1,'cugraph::uniform_nbr_sample(raft::handle_t const  &amp;handle, graph_view_t const  &amp;graph_view, typename graph_view_t::vertex_type const  *ptr_d_starting_vertices, gpu_t const  *ptr_d_ranks, size_t num_starting_vertices, std::vector&lt; int &gt; const  &amp;h_fan_out, bool with_replacement=true)'],['../namespacecugraph.html#acef2469af4c5fd470ddb58b65f47af12',1,'cugraph::uniform_nbr_sample(raft::handle_t const  &amp;handle, graph_view_t&lt; vertex_t, edge_t, weight_t, store_transposed, multi_gpu &gt; const  &amp;graph_view, raft::device_span&lt; vertex_t &gt; starting_vertices, raft::host_span&lt; const int &gt; fan_out, bool with_replacement=true, uint64_t seed=0)']]],
  ['unrenumber_5fint_5fvertices_842',['unrenumber_int_vertices',['../namespacecugraph.html#a684545dbb07a8981e1b6fcafaa369376',1,'cugraph']]],
  ['unrenumber_5flocal_5fint_5fedges_843',['unrenumber_local_int_edges',['../namespacecugraph.html#a6738df2e950f62bda7fdfbcf0a2ec440',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_srcs, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_dsts, std::vector&lt; size_t &gt; const  &amp;edgelist_edge_counts, vertex_t const  *renumber_map_labels, std::vector&lt; vertex_t &gt; const  &amp;vertex_partition_range_lasts, std::optional&lt; std::vector&lt; std::vector&lt; size_t &gt;&gt;&gt; const  &amp;edgelist_intra_partition_segment_offsets, bool do_expensive_check=false)'],['../namespacecugraph.html#ac18d945222b132c054d2bc748d144872',1,'cugraph::unrenumber_local_int_edges(raft::handle_t const  &amp;handle, vertex_t *edgelist_srcs, vertex_t *edgelist_dsts, size_t num_edgelist_edges, vertex_t const  *renumber_map_labels, vertex_t num_vertices, bool do_expensive_check=false)']]],
  ['unrenumber_5flocal_5fint_5fvertices_844',['unrenumber_local_int_vertices',['../namespacecugraph.html#ab2d2829de3b33d7f394c8a1ff5169ca5',1,'cugraph']]],
  ['update_5fedge_5fpartition_5fdst_5fproperty_845',['update_edge_partition_dst_property',['../namespacecugraph.html#aa2cb5d2a38763985faec04ed7ebaadc2',1,'cugraph::update_edge_partition_dst_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexPropertyInputIterator vertex_property_input_first, edge_partition_dst_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_dst_property_output)'],['../namespacecugraph.html#ae78580051c2b007aef1259d81662411a',1,'cugraph::update_edge_partition_dst_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexIterator vertex_first, VertexIterator vertex_last, VertexPropertyInputIterator vertex_property_input_first, edge_partition_dst_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_dst_property_output)']]],
  ['update_5fedge_5fpartition_5fsrc_5fproperty_846',['update_edge_partition_src_property',['../namespacecugraph.html#aa463cf3536adb5598740a26c27540f9c',1,'cugraph::update_edge_partition_src_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexPropertyInputIterator vertex_property_input_first, edge_partition_src_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_src_property_output)'],['../namespacecugraph.html#a343d77203166508f99dc83f29d72df7e',1,'cugraph::update_edge_partition_src_property(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexIterator vertex_first, VertexIterator vertex_last, VertexPropertyInputIterator vertex_property_input_first, edge_partition_src_property_t&lt; GraphViewType, typename std::iterator_traits&lt; VertexPropertyInputIterator &gt;::value_type &gt; &amp;edge_partition_src_property_output)']]],
  ['update_5fv_5ffrontier_5ffrom_5foutgoing_5fe_847',['update_v_frontier_from_outgoing_e',['../namespacecugraph.html#ac8bb97bd2961296b1f6515fabeb4f22e',1,'cugraph']]],
  ['updatedevice_848',['updateDevice',['../group__Copy.html#ga18a265a5eb16da13a51f486fe5e3acb7',1,'MLCommon']]],
  ['updatehost_849',['updateHost',['../group__Copy.html#ga9c1498ebc5825f9e63a9de94ced042d5',1,'MLCommon']]]
];
