var searchData=
[
  ['random_5fwalks_823',['random_walks',['../namespacecugraph.html#a179206df4869b42d6e5a7c28bcabcfd4',1,'cugraph']]],
  ['reduce_5fv_824',['reduce_v',['../namespacecugraph.html#a446664d4cca5e3b63474fe0ada4afb24',1,'cugraph::reduce_v(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexValueInputIterator vertex_value_input_first, T init, ReduceOp reduce_op)'],['../namespacecugraph.html#a748baa1e69a08edb98eeb1043e6cfce7',1,'cugraph::reduce_v(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexValueInputIterator vertex_value_input_first, T init)'],['../namespacecugraph.html#a36dd203e3141cfdf26dcd129ec0098c3',1,'cugraph::reduce_v(raft::handle_t const &amp;handle, GraphViewType const &amp;graph_view, VertexValueInputIterator vertex_value_input_first)']]],
  ['relabel_825',['relabel',['../namespacecugraph.html#a7e8d4a7f63d0e7e3a9b17f81acc09403',1,'cugraph']]],
  ['renumber_5fedgelist_826',['renumber_edgelist',['../namespacecugraph.html#a810db2803a936e0ea35df9ef37b3c606',1,'cugraph::renumber_edgelist(raft::handle_t const  &amp;handle, std::optional&lt; rmm::device_uvector&lt; vertex_t &gt;&gt; &amp;&amp;local_vertices, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_srcs, std::vector&lt; vertex_t * &gt; const  &amp;edgelist_dsts, std::vector&lt; edge_t &gt; const  &amp;edgelist_edge_counts, std::optional&lt; std::vector&lt; std::vector&lt; edge_t &gt;&gt;&gt; const  &amp;edgelist_intra_partition_segment_offsets, bool store_transposed, bool do_expensive_check=false)'],['../namespacecugraph.html#a6c8072d7e5d99f87ae566939cd1325ae',1,'cugraph::renumber_edgelist(raft::handle_t const  &amp;handle, std::optional&lt; rmm::device_uvector&lt; vertex_t &gt;&gt; &amp;&amp;vertices, vertex_t *edgelist_srcs, vertex_t *edgelist_dsts, edge_t num_edgelist_edges, bool store_transposed, bool do_expensive_check=false)']]],
  ['renumber_5fext_5fvertices_827',['renumber_ext_vertices',['../namespacecugraph.html#a431a64199aca6af92b8f9a5b62d0168f',1,'cugraph']]],
  ['renumber_5flocal_5fext_5fvertices_828',['renumber_local_ext_vertices',['../namespacecugraph.html#a92774376fe8db9017e0dc07993c0a00d',1,'cugraph']]]
];
