var searchData=
[
  ['scalar_2087',['scalar',['../classcudf_1_1scalar.html',1,'cudf']]],
  ['scalar_5fdevice_5fview_5fbase_2088',['scalar_device_view_base',['../classcudf_1_1detail_1_1scalar__device__view__base.html',1,'cudf::detail']]],
  ['scaled_5finteger_2089',['scaled_integer',['../structnumeric_1_1scaled__integer.html',1,'numeric']]],
  ['scan_5faggregation_2090',['scan_aggregation',['../classcudf_1_1scan__aggregation.html',1,'cudf']]],
  ['scan_5frequest_2091',['scan_request',['../structcudf_1_1groupby_1_1scan__request.html',1,'cudf::groupby']]],
  ['schema_5felement_2092',['schema_element',['../structcudf_1_1io_1_1schema__element.html',1,'cudf::io']]],
  ['segmented_5freduce_5faggregation_2093',['segmented_reduce_aggregation',['../classcudf_1_1segmented__reduce__aggregation.html',1,'cudf']]],
  ['self_5fcomparator_2094',['self_comparator',['../classcudf_1_1experimental_1_1row_1_1lexicographic_1_1self__comparator.html',1,'cudf::experimental::row::lexicographic::self_comparator'],['../classcudf_1_1experimental_1_1row_1_1equality_1_1self__comparator.html',1,'cudf::experimental::row::equality::self_comparator']]],
  ['sink_5finfo_2095',['sink_info',['../structcudf_1_1io_1_1sink__info.html',1,'cudf::io']]],
  ['sorting_5fphysical_5felement_5fcomparator_2096',['sorting_physical_element_comparator',['../structcudf_1_1experimental_1_1row_1_1lexicographic_1_1sorting__physical__element__comparator.html',1,'cudf::experimental::row::lexicographic']]],
  ['source_5finfo_2097',['source_info',['../structcudf_1_1io_1_1source__info.html',1,'cudf::io']]],
  ['span_5fbase_2098',['span_base',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20detail_3a_3adremel_5fdevice_5fview_20const_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20detail_3a_3adremel_5fdevice_5fview_20const_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_2099',['span_base&lt; detail::dremel_device_view const, cudf::dynamic_extent, device_span&lt; detail::dremel_device_view const, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20t_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20t_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_2100',['span_base&lt; T, cudf::dynamic_extent, device_span&lt; T, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20t_2c_20cudf_3a_3adynamic_5fextent_2c_20host_5fspan_3c_20t_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_2101',['span_base&lt; T, cudf::dynamic_extent, host_span&lt; T, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['stack_5ftrace_2102',['stack_trace',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1detail_1_1stack__trace.html',1,'rmm::detail']]],
  ['statistics_5fresource_5fadaptor_2103',['statistics_resource_adaptor',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1statistics__resource__adaptor.html',1,'rmm::mr']]],
  ['stream_5fallocator_5fadaptor_2104',['stream_allocator_adaptor',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1stream__allocator__adaptor.html',1,'rmm::mr']]],
  ['stream_5fevent_5fpair_2105',['stream_event_pair',['https://docs.rapids.ai/api/librmm/22.10/structrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource_1_1stream__event__pair.html',1,'rmm::mr::detail::stream_ordered_memory_resource']]],
  ['stream_5fordered_5fmemory_5fresource_2106',['stream_ordered_memory_resource',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource.html',1,'rmm::mr::detail']]],
  ['stream_5fordered_5fmemory_5fresource_3c_20fixed_5fsize_5fmemory_5fresource_3c_20upstream_20_3e_2c_20detail_3a_3afixed_5fsize_5ffree_5flist_20_3e_2107',['stream_ordered_memory_resource&lt; fixed_size_memory_resource&lt; Upstream &gt;, detail::fixed_size_free_list &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource.html',1,'']]],
  ['stream_5fordered_5fmemory_5fresource_3c_20pool_5fmemory_5fresource_3c_20upstream_20_3e_2c_20detail_3a_3acoalescing_5ffree_5flist_20_3e_2108',['stream_ordered_memory_resource&lt; pool_memory_resource&lt; Upstream &gt;, detail::coalescing_free_list &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1detail_1_1stream__ordered__memory__resource.html',1,'']]],
  ['string_5fscalar_2109',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fscalar_5fdevice_5fview_2110',['string_scalar_device_view',['../classcudf_1_1string__scalar__device__view.html',1,'cudf']]],
  ['string_5fstatistics_2111',['string_statistics',['../structcudf_1_1io_1_1string__statistics.html',1,'cudf::io']]],
  ['string_5fview_2112',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_2113',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['strings_5fcolumn_5fwrapper_2114',['strings_column_wrapper',['../classcudf_1_1test_1_1strings__column__wrapper.html',1,'cudf::test']]],
  ['strong_5findex_5fiterator_2115',['strong_index_iterator',['../structcudf_1_1experimental_1_1row_1_1strong__index__iterator.html',1,'cudf::experimental::row']]],
  ['struct_5fscalar_2116',['struct_scalar',['../classcudf_1_1struct__scalar.html',1,'cudf']]],
  ['struct_5fview_2117',['struct_view',['../classcudf_1_1struct__view.html',1,'cudf']]],
  ['structs_5fcolumn_5fdevice_5fview_2118',['structs_column_device_view',['../classcudf_1_1detail_1_1structs__column__device__view.html',1,'cudf::detail']]],
  ['structs_5fcolumn_5fview_2119',['structs_column_view',['../classcudf_1_1structs__column__view.html',1,'cudf']]],
  ['structs_5fcolumn_5fwrapper_2120',['structs_column_wrapper',['../classcudf_1_1test_1_1structs__column__wrapper.html',1,'cudf::test']]],
  ['sum_5fstatistics_2121',['sum_statistics',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20double_20_3e_2122',['sum_statistics&lt; double &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20int64_5ft_20_3e_2123',['sum_statistics&lt; int64_t &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20std_3a_3astring_20_3e_2124',['sum_statistics&lt; std::string &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20uint64_5ft_20_3e_2125',['sum_statistics&lt; uint64_t &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['superblock_2126',['superblock',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1detail_1_1arena_1_1superblock.html',1,'rmm::mr::detail::arena']]]
];
