var searchData=
[
  ['data_5fchunk_5freader_1921',['data_chunk_reader',['../classcudf_1_1io_1_1text_1_1data__chunk__reader.html',1,'cudf::io::text']]],
  ['data_5fchunk_5fsource_1922',['data_chunk_source',['../classcudf_1_1io_1_1text_1_1data__chunk__source.html',1,'cudf::io::text']]],
  ['data_5fsink_1923',['data_sink',['../classcudf_1_1io_1_1data__sink.html',1,'cudf::io']]],
  ['data_5ftype_1924',['data_type',['../classcudf_1_1data__type.html',1,'cudf']]],
  ['datasource_1925',['datasource',['../classcudf_1_1io_1_1datasource.html',1,'cudf::io']]],
  ['decimal_5fstatistics_1926',['decimal_statistics',['../structcudf_1_1io_1_1decimal__statistics.html',1,'cudf::io']]],
  ['device_5fbuffer_1927',['device_buffer',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__buffer.html',1,'rmm']]],
  ['device_5fdata_5fchunk_1928',['device_data_chunk',['../classcudf_1_1io_1_1text_1_1device__data__chunk.html',1,'cudf::io::text']]],
  ['device_5fmemory_5fresource_1929',['device_memory_resource',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1mr_1_1device__memory__resource.html',1,'rmm::mr']]],
  ['device_5frow_5fcomparator_1930',['device_row_comparator',['../classcudf_1_1experimental_1_1row_1_1lexicographic_1_1device__row__comparator.html',1,'cudf::experimental::row::lexicographic::device_row_comparator&lt; Nullate, PhysicalElementComparator &gt;'],['../classcudf_1_1experimental_1_1row_1_1equality_1_1device__row__comparator.html',1,'cudf::experimental::row::equality::device_row_comparator&lt; Nullate, PhysicalEqualityComparator &gt;']]],
  ['device_5frow_5fhasher_1931',['device_row_hasher',['../classcudf_1_1experimental_1_1row_1_1hash_1_1device__row__hasher.html',1,'cudf::experimental::row::hash']]],
  ['device_5fscalar_1932',['device_scalar',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20bool_20_3e_1933',['device_scalar&lt; bool &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20rep_5ftype_20_3e_1934',['device_scalar&lt; rep_type &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20t_20_3e_1935',['device_scalar&lt; T &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fspan_1936',['device_span',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fuvector_1937',['device_uvector',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['device_5fuvector_3c_20null_5forder_20_3e_1938',['device_uvector&lt; null_order &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['device_5fuvector_3c_20order_20_3e_1939',['device_uvector&lt; order &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['device_5fuvector_3c_20size_5ftype_20_3e_1940',['device_uvector&lt; size_type &gt;',['https://docs.rapids.ai/api/librmm/22.10/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['dictionary_5fcolumn_5fview_1941',['dictionary_column_view',['../classcudf_1_1dictionary__column__view.html',1,'cudf']]],
  ['dictionary_5fcolumn_5fwrapper_1942',['dictionary_column_wrapper',['../classcudf_1_1test_1_1dictionary__column__wrapper.html',1,'cudf::test']]],
  ['dictionary_5fcolumn_5fwrapper_3c_20std_3a_3astring_20_3e_1943',['dictionary_column_wrapper&lt; std::string &gt;',['../classcudf_1_1test_1_1dictionary__column__wrapper_3_01std_1_1string_01_4.html',1,'cudf::test']]],
  ['dictionary_5fwrapper_1944',['dictionary_wrapper',['../structcudf_1_1dictionary__wrapper.html',1,'cudf']]],
  ['dispatch_5fstorage_5ftype_1945',['dispatch_storage_type',['../structcudf_1_1dispatch__storage__type.html',1,'cudf']]],
  ['dispatch_5fvoid_5fif_5fnested_1946',['dispatch_void_if_nested',['../structcudf_1_1experimental_1_1dispatch__void__if__nested.html',1,'cudf::experimental']]],
  ['double_5fstatistics_1947',['double_statistics',['../structcudf_1_1io_1_1double__statistics.html',1,'cudf::io']]],
  ['duration_5fscalar_1948',['duration_scalar',['../classcudf_1_1duration__scalar.html',1,'cudf']]],
  ['duration_5fscalar_5fdevice_5fview_1949',['duration_scalar_device_view',['../classcudf_1_1duration__scalar__device__view.html',1,'cudf']]],
  ['dynamic_1950',['DYNAMIC',['../structcudf_1_1nullate_1_1DYNAMIC.html',1,'cudf::nullate']]],
  ['dynamic_5fload_5fruntime_1951',['dynamic_load_runtime',['https://docs.rapids.ai/api/librmm/22.10/structrmm_1_1detail_1_1dynamic__load__runtime.html',1,'rmm::detail']]]
];
