var searchData=
[
  ['data_5fchunk_5freader_1933',['data_chunk_reader',['../classcudf_1_1io_1_1text_1_1data__chunk__reader.html',1,'cudf::io::text']]],
  ['data_5fchunk_5fsource_1934',['data_chunk_source',['../classcudf_1_1io_1_1text_1_1data__chunk__source.html',1,'cudf::io::text']]],
  ['data_5fsink_1935',['data_sink',['../classcudf_1_1io_1_1data__sink.html',1,'cudf::io']]],
  ['data_5ftype_1936',['data_type',['../classcudf_1_1data__type.html',1,'cudf']]],
  ['datasource_1937',['datasource',['../classcudf_1_1io_1_1datasource.html',1,'cudf::io']]],
  ['decimal_5fstatistics_1938',['decimal_statistics',['../structcudf_1_1io_1_1decimal__statistics.html',1,'cudf::io']]],
  ['device_5fbuffer_1939',['device_buffer',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__buffer.html',1,'rmm']]],
  ['device_5fdata_5fchunk_1940',['device_data_chunk',['../classcudf_1_1io_1_1text_1_1device__data__chunk.html',1,'cudf::io::text']]],
  ['device_5fmemory_5fresource_1941',['device_memory_resource',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1mr_1_1device__memory__resource.html',1,'rmm::mr']]],
  ['device_5frow_5fcomparator_1942',['device_row_comparator',['../classcudf_1_1experimental_1_1row_1_1lexicographic_1_1device__row__comparator.html',1,'cudf::experimental::row::lexicographic::device_row_comparator&lt; has_nested_columns, Nullate, PhysicalElementComparator &gt;'],['../classcudf_1_1experimental_1_1row_1_1equality_1_1device__row__comparator.html',1,'cudf::experimental::row::equality::device_row_comparator&lt; Nullate, PhysicalEqualityComparator &gt;']]],
  ['device_5frow_5fhasher_1943',['device_row_hasher',['../classcudf_1_1experimental_1_1row_1_1hash_1_1device__row__hasher.html',1,'cudf::experimental::row::hash']]],
  ['device_5fscalar_1944',['device_scalar',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20bool_20_3e_1945',['device_scalar&lt; bool &gt;',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20rep_5ftype_20_3e_1946',['device_scalar&lt; rep_type &gt;',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fscalar_3c_20t_20_3e_1947',['device_scalar&lt; T &gt;',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__scalar.html',1,'rmm']]],
  ['device_5fspan_1948',['device_span',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fspan_3c_20detail_3a_3adremel_5fdevice_5fview_20const_20_3e_1949',['device_span&lt; detail::dremel_device_view const &gt;',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fuvector_1950',['device_uvector',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['device_5fuvector_3c_20null_5forder_20_3e_1951',['device_uvector&lt; null_order &gt;',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['device_5fuvector_3c_20order_20_3e_1952',['device_uvector&lt; order &gt;',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['device_5fuvector_3c_20size_5ftype_20_3e_1953',['device_uvector&lt; size_type &gt;',['https://docs.rapids.ai/api/librmm/22.12/classrmm_1_1device__uvector.html',1,'rmm']]],
  ['dictionary_5fcolumn_5fview_1954',['dictionary_column_view',['../classcudf_1_1dictionary__column__view.html',1,'cudf']]],
  ['dictionary_5fcolumn_5fwrapper_1955',['dictionary_column_wrapper',['../classcudf_1_1test_1_1dictionary__column__wrapper.html',1,'cudf::test']]],
  ['dictionary_5fcolumn_5fwrapper_3c_20std_3a_3astring_20_3e_1956',['dictionary_column_wrapper&lt; std::string &gt;',['../classcudf_1_1test_1_1dictionary__column__wrapper_3_01std_1_1string_01_4.html',1,'cudf::test']]],
  ['dictionary_5fwrapper_1957',['dictionary_wrapper',['../structcudf_1_1dictionary__wrapper.html',1,'cudf']]],
  ['dispatch_5fstorage_5ftype_1958',['dispatch_storage_type',['../structcudf_1_1dispatch__storage__type.html',1,'cudf']]],
  ['dispatch_5fvoid_5fif_5fnested_1959',['dispatch_void_if_nested',['../structcudf_1_1experimental_1_1dispatch__void__if__nested.html',1,'cudf::experimental']]],
  ['double_5fstatistics_1960',['double_statistics',['../structcudf_1_1io_1_1double__statistics.html',1,'cudf::io']]],
  ['duration_5fscalar_1961',['duration_scalar',['../classcudf_1_1duration__scalar.html',1,'cudf']]],
  ['duration_5fscalar_5fdevice_5fview_1962',['duration_scalar_device_view',['../classcudf_1_1duration__scalar__device__view.html',1,'cudf']]],
  ['dynamic_1963',['DYNAMIC',['../structcudf_1_1nullate_1_1DYNAMIC.html',1,'cudf::nullate']]],
  ['dynamic_5fload_5fruntime_1964',['dynamic_load_runtime',['https://docs.rapids.ai/api/librmm/22.12/structrmm_1_1detail_1_1dynamic__load__runtime.html',1,'rmm::detail']]]
];
